cc_binary(
    name = "empty_class",
    srcs = [
        "empty_class.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "ebo",
    srcs = [
        "ebo.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "pod",
    srcs = [
        "pod.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "pod_with_access_specifier",
    srcs = [
        "pod_with_access_specifier.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "pod_with_methods",
    srcs = [
        "pod_with_methods.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "single_inheritance",
    srcs = [
        "single_inheritance.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "polym",
    srcs = [
        "polym.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "multi_inheritance",
    srcs = [
        "multi_inheritance.cc",
    ],
    deps = ["//base"],
)

cc_binary(
    name = "virtual_inheritance",
    srcs = [
        "virtual_inheritance.cc",
    ],
    deps = ["//base"],
)
